# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWTfNWAbCLdDXc2x4RTMawL37C9TSfEP
"""

import pandas as pd;

df = pd.read_csv ('dados_nao_tratados.csv')

#tratamento true/false
df['ativo'] = df ['ativo'].astype(str).str.strip().str.lower().map({'sim' : True, 'Sim' : True,
'true' : True, 'yes' : True, 'não' : False, 'nao': False, 'false': False, 'e' : None });

#tratamento de valores inconsistentes
df['idade'] = pd.to_numeric(df['idade'], errors = 'coerce').astype('Int64');
df['nota'] = pd.to_numeric(df['nota'], errors = 'coerce').astype('Float64');

#tratamento de dados
df['data_inscricao'] = pd.to_datetime(df['data_inscricao'], errors = 'coerce')

df = df.dropna()

df.to_csv ('dados_tratados.csv', index=False)

df

